import type { Metadata } from "next";
import { Figtree } from "next/font/google"
import "./globals.css";
import { Suspense } from "react";

const figtree = Figtree({
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Reflect",
  description: "Generated by create next app",
  icons: "images/logo.png",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${figtree.className} antialiased`}
      > <Suspense fallback={<div>Loading...</div>}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
